### ISSUE TITLE
Working with two stage networks

### ISSUE THREAD

**Issue by rssaketh** [megvii-research/Co-mining#1]
Hi,
Great work!
I'm curious if this method works for two stage detectors as well and if it does, what precautions should one take to run it with two stage detectors?
thanks

**Comment by vaesl** [comment]
> Hi, Great work! I'm curious if this method works for two stage detectors as well and if it does, what precautions should one take to run it with two stage detectors? thanks

I think one direct idea is to employ Co-mining in the first stage (such as RPN) of two-stage methods since RPN can be regarded as a one-stage object detector. In this way, we can generate more pseudo positive labels for the second stage.
